language: php
php:
    - 7.0
    - 7.1
    - 7.2
    - hhvm

install:
    - composer install --ignore-platform-reqs
    - composer require satooshi/php-coveralls --dev --ignore-platform-reqs

script:
    - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
