language: php
php:
    - 7.0
    - 7.1
    - 7.2

env:
    matrix:
        - DEPENDENCIES="high"
        - DEPENDENCIES="low"

install:
    - if [[ "$DEPENDENCIES" = 'high' ]]; then composer install; fi
    - if [[ "$DEPENDENCIES" = 'low' ]]; then composer install --prefer-lowest; fi
    - composer require satooshi/php-coveralls --dev

script:
    - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v

notifications:
    email: false
