language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly
    - hhvm

env:
    - SWIFTMAILER_VERSION=4 DEPENDENCIES=high
    - SWIFTMAILER_VERSION=4 DEPENDENCIES=low
    - SWIFTMAILER_VERSION=5 DEPENDENCIES=high
    - SWIFTMAILER_VERSION=5 DEPENDENCIES=low
    - SWIFTMAILER_VERSION=6 DEPENDENCIES=high
    - SWIFTMAILER_VERSION=6 DEPENDENCIES=low

matrix:
    exclude:
        - php: 5.6
          env: SWIFTMAILER_VERSION=6 DEPENDENCIES=high
        - php: 5.6
          env: SWIFTMAILER_VERSION=6 DEPENDENCIES=low
    allow_failures:
        - php: hhvm
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer require "swiftmailer/swiftmailer ^$SWIFTMAILER_VERSION" --no-update
    - if [[ "$DEPENDENCIES" = 'high' ]]; then composer update; fi
    - if [[ "$DEPENDENCIES" = 'low' ]]; then composer update --prefer-lowest; fi
    - composer require php-coveralls/php-coveralls '^2.0' --dev

script:
    - php vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
    - php vendor/bin/php-coveralls -v

notifications:
    email: false
